### ISSUE TITLE
Some features are disabled.

### ISSUE THREAD

**Issue by rickyAwe** [jef/nvidia-snatcher#155]

**Comment by geman220** [comment]
Any specific info you can provide?

**Comment by rickyAwe** [comment]
The text I input disappeared sorry. My OS is Windows10, I used Git Bash and had your codes cloned, installed correctly. When running however, only the Nvidia store will give feedbacks every 10 seconds. For the rest of the eight stores/sites, there are 8 initial error 'INFO: Could not find files for the given pattern(s)'

**Comment by geman220** [comment]
You can ignore `INFO: Could not find files for the given pattern(s)` can you paste your `.env`

**Comment by rickyAwe** [comment]
DISCORD_NOTIFY_GROUP="@here"
DISCORD_WEB_HOOK="https://discordapp.com/api/webhooks/23123123123/5dfsdfh3h2j5hdfhsdfsdhj55jf"
EMAIL_USERNAME="youremail@gmail.com"
EMAIL_PASSWORD="secretpassword"
HEADLESS="true"
LOG_LEVEL="info"
OPEN_BROWSER="true"
PAGE_TIMEOUT="30000"
PHONE_NUMBER="1234567890"
PHONE_CARRIER="tmobile"
PLAY_SOUND="notification.mp3"
PUSHOVER_TOKEN="123pushover-token456"
PUSHOVER_USER="123pushover-user-key"
PAGE_SLEEP_MIN="5000"
PAGE_SLEEP_MAX="10000"
SHOW_ONLY_BRANDS="evga"
SHOW_ONLY_SERIES="3080"
SLACK_CHANNEL="SlackChannelName"
SLACK_TOKEN="slack-token"
STORES="bestbuy,bandh,nvidia"
SCREENSHOT="true"
TELEGRAM_ACCESS_TOKEN=""
TELEGRAM_CHAT_ID="1234"
USER_AGENT=(not sure if it's safe to show content in this row, I am a coding noob, if you need it nontheless let me know)

**Comment by geman220** [comment]
`SHOW_ONLY_BRANDS="evga"` Do you actually only want EVGA?  Because if so searching the nvidia store isn't going to work.  You are also only searching 3 stores `STORES="bestbuy,bandh,nvidia"` if you want to search additional stores change your `STORES=` to reflect those stores.  I'm assuming you aren't actually using any of these configuration options since you left the defaults.  Comment out everything you aren't using with `#` like I have done here.

# DISCORD_NOTIFY_GROUP="@here"
# DISCORD_WEB_HOOK="https://discordapp.com/api/webhooks/23123123123/5dfsdfh3h2j5hdfhsdfsdhj55jf"
# EMAIL_USERNAME="youremail@gmail.com"
# EMAIL_PASSWORD="secretpassword"
# HEADLESS="true"
# LOG_LEVEL="info"
OPEN_BROWSER="true"
# PAGE_TIMEOUT="30000"
# PHONE_NUMBER="1234567890"
# PHONE_CARRIER="tmobile"
# PLAY_SOUND="notification.mp3"
# PUSHOVER_TOKEN="123pushover-token456"
# PUSHOVER_USER="123pushover-user-key"
# PAGE_SLEEP_MIN="5000"
# PAGE_SLEEP_MAX="10000"
# SHOW_ONLY_BRANDS="evga"
SHOW_ONLY_SERIES="3080"
# SLACK_CHANNEL="SlackChannelName"
# SLACK_TOKEN="slack-token"
STORES="bestbuy,bandh,nvidia"
SCREENSHOT="true"
# TELEGRAM_ACCESS_TOKEN=""
# TELEGRAM_CHAT_ID="1234"
# USER_AGENT=(not sure if it's safe to show content in this row, I am a coding noob, if you need it nontheless let me know)

**Comment by rickyAwe** [comment]
I didn't modify the .env file, kept it as downloaded, was I supposed to temper with it to widen the search range? (I think I see the problems here now, it was on me)

**Comment by rickyAwe** [comment]
I see how I can fix it now, thanks for the help, also sorry for the wrong tags..

**Comment by geman220** [comment]
No problem.
