### ISSUE TITLE
AUTO ADD TO CART - LINKS

### ISSUE THREAD

**Issue by Ascendin81** [jef/nvidia-snatcher#158]
### Description

AUTO ADD TO CART LINKS

### Possible solution

https://docs.google.com/spreadsheets/d/1Pwk63QtbNWF0A1geaKBvgWQ6p2sItIMbHUdhbNmQ2cw/edit#gid=0

**Comment by geman220** [comment]
I believe Best Buy already has these auto-add links, but they are slightly different. `https://api.bestbuy.com/click/-/6432400/cart` for example already exists instead of `https://api.bestbuy.com/click/5592e2b895800000/6432400/cart`

I submitted a PR that was merged to move the `cartUrl` into 'Link` instead of `Store` so I could add all of these auto adds relatively easily (just time consuming)  @jef thoughts?

**Comment by geman220** [comment]
The Amazon links are not auto add to cart links, a user still needs to hit `Okay` this actually might be worse than the product page since the product page should allow 1-click-buy if the user has that setup with Amazon.com  Best Buy already had auto add to cart functionality, so I modified the code to auto add to cart for Newegg.  See PR #153
