### ISSUE TITLE
High data usage

### ISSUE THREAD

**Issue by g1forfun** [jef/nvidia-snatcher#164]
### Description

Using a ton of bandwidth. May be a concern to those of us with data caps on our usage.
Windows 10 2004

### Possible solution

Not sure why this is using so much bandwidth but you can see the various chrome.exe processes sending and receiving tons of data when nvidia-snatcher is running.

Just wanted to bring it to your attention with some screenshots. Thanks for making this!
![nvidia-snatcher-data-usage](https://user-images.githubusercontent.com/2007992/93794731-791a6e00-fc06-11ea-9102-31f290dd0457.PNG)
![nvidia-snatcher-data-usage](https://user-images.githubusercontent.com/2007992/93798537-db29a200-fc0b-11ea-88d6-aced7dd07dfa.jpg)

**Comment by jef** [comment]
Thanks! We know to some degree this is happening. I appreciate the screenshots!

Background: In chrome, each tab is a process, hence all the `chrome.exe`. Each tab is downloading the page's assets, without any caching.

So it's downloading everything, everytime. This is very resource heavy.

Until we change the bot to do requests that mock a webpage without actually opening Chrome, this will continue to a problem (except for `nvidia` store, because it's not using a webpage).
