### ISSUE TITLE
Maximum Price Limit

### ISSUE THREAD

**Issue by AidanHockey5** [jef/nvidia-snatcher#165]
### Description

Only send an alert if an in-stock card is at or below a defined target price. This will reduce the amount of false-positives from various marketplace sellers listing their cards for unreasonable prices. A few sellers on Amazon seem to be notorious for this.

**Comment by jef** [comment]
This is going to be solved by parsing the selectors and getting prices. This will be an overall improvement on speed, price filtering and various other things.

This will be top priority on my workload.

Thanks!

**Comment by designgears** [comment]
Preferably this would have pricing set on each product with the option to set a price margin in the env so we can customize it.

**Comment by geman220** [comment]
A PR for a simliar concept has been submitted #173.  Instead of setting prices, it will allow sellers to be banned from the bot.  For example, `Sports Authentics` is a vendor that keeps triggering the bot.  I agree filtering by price limit is a better overall solution, but this PR should at least eliviate false-positives from Amazon.
