### ISSUE TITLE
Add support for a proxy or pool of IPs

### ISSUE THREAD

**Issue by aharris02** [jef/nvidia-snatcher#321]
### Description
Left image is a server on AWS. Right is powershell on my local computer. As far as I can tell, the AWS server's requests are blocked because the AWS region IP blocks are [easily discoverable](https://docs.aws.amazon.com/general/latest/gr/aws-ip-ranges.html).
![image](https://user-images.githubusercontent.com/12698673/94327920-131a4780-ff74-11ea-914f-f40d7da88167.png)

### Possible solution

I'm sure there are other solutions, but adding support for a rotating block of proxied IP addresses would help reduce blocks. This can be done in the app directly by changing the IP address each time the browser session is started and stopped. If we want to change the IP address for each query, that would need to be implemented as a separate proxy server.

https://scrapoxy.io/
https://zenscrape.com/how-to-build-a-simple-proxy-rotator-in-node-js/

**Comment by jef** [comment]
Related to https://github.com/jef/nvidia-snatcher/issues/113#issuecomment-695816283

**Comment by matjam** [comment]
clearly the next step is a worker mode where you can have workers running on multiple machines and they report back to the central node that then posts the actual status. So if you have 30 people all running the checker, you have good coverage, and if one person gets blocked, the others will still be ok.

**Comment by fabienvauchelles** [comment]
Hi, if you are interested, Scrapoxy 4 is out!

Scrapoxy is a open source proxy aggregator, allowing you to manage all proxies in one place 🎯, rather than 
spreading it across multiple scrapers 🕸️.

Smartly designed for efficient traffic routing 🔀, Scrapoxy minimizes #bans and boosts success rates 🚀.

The tech stack is built on the latest NodeJS, Typescript, utilizing the NestJS and Angular frameworks.

Here are the key features:

- ☁️ Cloud Providers with easy installation: Scrapoxy supports many cloud providers like AWS, Azure, or GCP.
- 🌐 Proxy Services: Scrapoxy supports many proxy services like Rayobyte, IPRoyal or Zyte.
- 💻 Hardware materials: Scrapoxy supports many 4G proxy farms hardware types, like Proxidize or XProxy.io.
- 📜 Free Proxy Lists: Scrapoxy supports lists of HTTP/HTTPS proxies and SOCKS4/SOCKS5 proxies.
- ⏰ Timeout free: Scrapoxy only routes traffic to online proxies to avoid inactive connection.
- 🔄 Auto-Rotate proxies: Scrapoxy automatically changes IP addresses at regular intervals.
- 🏃 Auto-Scale proxies: Scrapoxy monitors incoming traffic and automatically scales the number of proxies according to your needs.
- 🍪 Sticky sessions on Browser: Scrapoxy keeps the same IP address for a scraping session, even for browsers.
- 🚨 Ban management: Scrapoxy injects the name of the proxy into the HTTP responses.
- 📡 Traffic interception: Scrapoxy intercepts HTTP requests/responses to modify headers, keeping consistency in your scraping stack. It can add session cookies or specific headers like user-agent.
- 📊 Traffic monitoring: Scrapoxy measures incoming and outgoing traffic to provide an overview of your scraping session.
- 🌍 Coverage monitoring: Scrapoxy displays the geographic coverage of your proxies to better understand the global distribution of your proxies.
- 🚀 Easy-to-use and production-ready: Scrapoxy is suitable for both beginners and experts (Kubernetes / Helm).
- 🔓 Open Source: And of course, Scrapoxy is open source, under the MIT license.

Checkout https://scrapoxy.io/ !

**Comment by Mr-Tech-13** [comment]
I could play around with that today. Thanks for the update
