### ISSUE TITLE
Anyway to reduce data consumption?

### ISSUE THREAD

**Issue by fokeiro2020** [jef/nvidia-snatcher#350]
For some reason the bot consumes a lot of data, ran it for 1 to 2 mins and used over 200mb.  Is there a way to reduce this?

**Comment by MattTheTechLV** [comment]
If you look at the readme you can see all the options you can enter. Low Bandwidth mode is one of them. Should help considerably.

**Comment by fokeiro2020** [comment]
> If you look at the readme you can see all the options you can enter. Low Bandwidth mode is one of them. Should help considerably.

Didnt help, low bandwith set as true and srill uses same amlunt of data

**Comment by SeanSeanySean** [comment]
You can try to limit your scope to only the sites, brands and cards you're interested in. If you're only interested in Nvidia Founders edition, you can try to limit store to Nvidia API, which doesn't have to render the entire page in the background in order to see if any are available. I have the same issue, I have a request in for them to publish tables for specific brands and card SKU's so we can really refine our search to only the cards we're interested in, should cut down the network traffic. Once they do that, you can also decrease the frequency in which the tool revisits a store to also cut down on the number of data coming back in.
