### ISSUE TITLE
Nvidia-API should open and send the link to the product page when add-to-cart fails

### ISSUE THREAD

**Issue by tsumeone** [jef/nvidia-snatcher#408]
Currently when a product is found in stock at Nvidia-API the "auto add to cart" function will fail due to changes at nvidia's site.  A bigger issue is once that fails, nvidia-snatcher opens an incorrect URL and also sends an incorrect URL in telegram.  Neither URL takes the user to a page where the item can be added to the cart.  Instead, it should open and send the product page URL so the user can add the item to the cart directly.  For example, https://www.nvidia.com/en-us/geforce/graphics-cards/30-series/rtx-3080/ for the 3080

**Comment by andrewmackrodt** [comment]
There's a lot out misinformation in discord around what Nvidia API is capable of; it is compatible with the current revision of Nvidia's API which has remained stable since Thursday of last week. A card may fail to add to cart because Nvidia's servers cannot handle the traffic versus any incompatibility in snatcher. This is exactly the same problem users of Nvidia's website encounter, those who are able to add a product to their cart click on the checkout button and nothing happens. The cause of this is a 504 Gateway Timeout error when Nvidia try and make the stock reservations with Digital River against the users session token. Snatcher is aware of server failures Inn this use case and uses a conservative retry number of 10, controlled by `NVIDIA_ADD_TO_CART_ATTEMPTS`. I don't want to cause a denial of service attack against Nvidia by making this value large as there's no delay implemented and out of stock will cause a retry the same way a gateway timeout will, so the value is set to 10 to be considerate.

**Comment by tsumeone** [comment]
I was not aware of that, ty for the info.  I have mine set to 0 as I don't want it to bother trying to add to cart.  Either way, it goes to the "failed" part and opens / notifies with links that do not allow the user to add to cart so I still think the link opened and notified should be changed to the product page in that event.

**Comment by jef** [comment]
Pinned and locked the issue. Thanks for the detailed explanation @andrewmackrodt!
