### ISSUE TITLE
Question about running git pull.

### ISSUE THREAD

**Issue by afcoulthard** [jef/nvidia-snatcher#578]
I am trying to run git pull to make sure the code I am running is up to date, when I run it I get an error but I am not sure if it is working or not. 

I had previously an issue troubleshoot when my test notification was not working, in that I edited notification.ts, and I noticed that the error is mentioning that exact file. In order to get the git pull to work (if it is not working) do I need to remove that file or what can I exactly do?

Code:

PS C:\Users\afcou\desktop> cd .\nvidia-snatcher\
PS C:\Users\afcou\desktop\nvidia-snatcher> git pull
remote: Enumerating objects: 144, done.
remote: Counting objects: 100% (144/144), done.
remote: Compressing objects: 100% (22/22), done.
remote: Total 180 (delta 130), reused 125 (delta 122), pack-reused 36
Receiving objects: 100% (180/180), 262.78 KiB | 1.88 MiB/s, done.
Resolving deltas: 100% (137/137), completed with 39 local objects.
From https://github.com/jef/nvidia-snatcher
   d575b8b..503d76f  main           -> origin/main
 * [new branch]      dependabot/github_actions/amannn/action-semantic-pull-request-v2.1.0 -> origin/dependabot/github_actions/amannn/action-semantic-pull-request-v2.1.0
 * [new branch]      dependabot/npm_and_yarn/nodemon-2.0.6 -> origin/dependabot/npm_and_yarn/nodemon-2.0.6
 * [new branch]      dependabot/npm_and_yarn/xo-0.34.1 -> origin/dependabot/npm_and_yarn/xo-0.34.1
 + 2fcae51...0c1ff32 release-v1.6.0 -> origin/release-v1.6.0  (forced update)
_**error: Your local changes to the following files would be overwritten by merge:
        src/notification/notification.ts
Please commit your changes or stash them before you merge.
Aborting
Updating 6b9d8cd..503d76f**_
PS C:\Users\afcou\desktop\nvidia-snatcher>

**Comment by BeefMediumRare** [comment]
You changed `src/notification/notification.ts` do you want to keep that change?

**Comment by ogrrd** [comment]
It sounds like you know you don't want to keep the change, as you asked if you need to remove that file.

Not quite _remove_, but you do need to clear the changes you made.

There's ways to do this, here's one: `git checkout src/notification/notification.ts`.

This will tell git to check out the file from the git cache, thus removing your changes.

Then you can do a pull, although you don't need to pull all branches so just `git pull origin main`.

**Comment by afcoulthard** [comment]
> git pull origin main

Thank you ogrrd, once I complete the two above lines you mentioned, I am assuming I should make the same swap I made previously again; so that I can ensure my notifications are working with npm run test:notification.

**Comment by ogrrd** [comment]
It depends if that file has had changes made to it in the repo, and if those changes would clash with yours.

One thing you could do instead of my first suggestion would be to do `git stash`, this will put your changes to one side and make it possible to do a `git pull origin main` again. Once you do that, you can slide your changes back in by doing `git stash apply`. If the changes you made are compatible with any changes to the file in the repo, it'll then just receive your changes. If it clashes, it'll tell you about it and let you edit the new file to make the problem go away by seeing what's gone wrong.

**Comment by afcoulthard** [comment]
Hmm I may have made a mistake along the way cause now _npm run start_ results in an error too. I might just do a fresh install then.

**Comment by ogrrd** [comment]
Yeah that's a good idea mate. Don't forget to take a copy of your `.env` config file.

Or, to save you checking it out into a new directory, you could do a `git reset --hard` and it should bring you right back to fresh. This will discard any changes but leave your `.env` file as it was since that's not a tracked file (it's ignored).

**Comment by afcoulthard** [comment]
Thanks for the help ogrrd, if I had just waited for your quick response I might have saved myself the trouble of doing a fresh install haha.

**Comment by ogrrd** [comment]
No worries!

**Comment by jef** [comment]
Thanks for the help @ogrrd.

@afcoulthard another way to download and update is to download the latest as a zip file: https://github.com/jef/nvidia-snatcher/archive/main.zip

and run from that way. Same results as using `git`, but could be easier for you.
